[package]
name = "wgpu_crate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
wgpu = "26.0.1"

[dev-dependencies]
crossbeam-channel = "0.5.15"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
